#!/bin/bash
set -e

result_curl="`curl --silent http://hq.sinajs.cn/list=sh510050 | iconv -f gbk -t utf8`"
#echo ${result_curl}

detail_info=${result_curl#*\"}
detail_info=${detail_info%\"*}
IFS=","
result_array=($detail_info)
#echo ${result_array[*]}

p=${result_array[3]}
v=`echo ${result_array[9]}/10000 | bc`

#echo ${p}_${v}

export PS1="[\u@${p}_${v} \W]\\$"

